### PR TITLE
Fixes #20337 - Add pxe loader into discovery v2 API

### PR DESCRIPTION
**Pull request by rabajaj0509**

### CODE REVIEW

**Comment by rabajaj0509** [comment]
@lzap the tests failing are not relevant to this pr, can you please look into the matter ?

**Comment by lzap** [comment]
Ok you added loader to create REST call, it is actually not much used API, hosts are being created via Facts API. The most important endpoint is

    api :PUT, "/discovered_hosts/:id/", N_("Provision a discovered host")

Add it there. I don't see it:

```
[lzap@box hammer-cli]$ hammer discovery provision --help
Usage:
    hammer discovery provision [OPTIONS]

Options:
 --architecture ARCHITECTURE_NAME                        Architecture name
 --architecture-id ARCHITECTURE_ID                        
 --ask-root-password ASK_ROOT_PW                         One of true/false, yes/no, 1/0.
 --build BUILD                                           One of true/false, yes/no, 1/0.
 --capabilities CAPABILITIES                              
 --domain DOMAIN_NAME                                    Domain name
 --domain-id DOMAIN_ID                                   Numerical ID or domain name
 --enabled ENABLED                                       One of true/false, yes/no, 1/0.
 --environment ENVIRONMENT_NAME                          Environment name
 --environment-id ENVIRONMENT_ID                          
 --host-parameters-attributes HOST_PARAMETERS_ATTRIBUTES Comma separated list of values. Values containing comma should be quoted or escaped with backslash
 --hostgroup HOSTGROUP_NAME                              Hostgroup name
 --hostgroup-id HOSTGROUP_ID                              
 --hostgroup-title HOSTGROUP_TITLE                       Hostgroup title
 --id ID                                                  
 --image IMAGE_NAME                                      Name to search by
 --image-id IMAGE_ID                                      
 --interface INTERFACE                                   Interface parameters
                                                         Comma-separated list of key=value.
                                                         Can be specified multiple times.
 --ip IP                                                 Not required if using a subnet with DHCP proxy
 --mac MAC                                               Not required if it’s a virtual machine
 --managed MANAGED                                       One of true/false, yes/no, 1/0.
 --medium MEDIUM_NAME                                    Medium name
 --medium-id MEDIUM_ID                                    
 --model MODEL_NAME                                      Model name
 --model-id MODEL_ID                                      
 --name NAME                                             Name to search by
 --new-name NEW_NAME                                      
 --operatingsystem OPERATINGSYSTEM_TITLE                 Operating system title
 --operatingsystem-id OPERATINGSYSTEM_ID                  
 --overwrite OVERWRITE                                   One of true/false, yes/no, 1/0.
 --owner-id OWNER_ID                                      
 --parameters PARAMS                                     Host parameters
                                                         Comma-separated list of key=value.
 --partition-table PARTITION_TABLE_NAME                  Partition table name
 --partition-table-id PARTITION_TABLE_ID                  
 --progress-report-id PROGRESS_REPORT_ID                 UUID to track orchestration tasks status, GET /api/orchestration/:UUID/tasks
 --provision-method METHOD                               Possible value(s): 'build', 'image'
 --puppet-ca-proxy-id PUPPET_CA_PROXY_ID                  
 --puppet-proxy-id PUPPET_PROXY_ID                        
 --puppetclass-ids PUPPETCLASS_IDS                       Comma separated list of values. Values containing comma should be quoted or escaped with backslash
 --root-password ROOT_PW                                  
 --sp-subnet-id SP_SUBNET_ID                              
 --subnet SUBNET_NAME                                    Subnet name
 --subnet-id SUBNET_ID                                    
 -h, --help                                              Print help
```

Then create a host:

```
[lzap@box hammer-cli]$ hammer-quick discovery provision --name mac52b3dfbd53ed --hostgroup "CentOS 7.0" --pxe-loader XYZ
Host created
```

**Review by lzap — CHANGES_REQUESTED** [review]
Add to PUT endpoint please.

**Comment by rabajaj0509** [comment]
[test]

**Comment by lzap** [comment]
Gonna [test] this next week, sorry for the delay!

**Comment by lzap** [comment]
We can hopefully [test] now.

**Comment by rabajaj0509** [comment]
Looks like : 

pxe_loader

**Comment by lzap** [comment]
Please reword the help text to:

    DHCP filename option ("PXELinux", "PXEGrub2 UEFI", "Grub2 UEFI SecureBoot" ...)

So users immediately see what the options are

**Comment by lzap** [comment]
Oh well it lists it, then just do

    DHCP filename option (PXELinux or PXEGrub2 UEFI by default)

**Comment by lzap** [comment]
And it works!

**Pull request merged**
