### PR TITLE
fixes #25846 - rhel kexec: fix undefined append variable

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by timogoebel** [comment]
In a follow up ticket we have to fix kexec for 1.20. I believe it's broken due to the new template engine. But have not had the time to check.

**Comment by timogoebel** [comment]
This should be the broken line: https://github.com/theforeman/foreman_discovery/blob/1f9721f71ece304838dcc0a1f6fef0080488bacf/app/views/foreman_discovery/redhat_kexec.erb#L47

**Comment by lzap** [comment]
Thanks Timo, this is just messed commit 1f9721f71ece304838dcc0a1f6fef0080488bacf by me.

I wanted to get rid of the extra "append" variable and store it in "options", can you do this instead:

```diff
diff --git a/app/views/foreman_discovery/redhat_kexec.erb b/app/views/foreman_discovery/redhat_kexec.erb
index fa3f457..be68d9c 100644
--- a/app/views/foreman_discovery/redhat_kexec.erb
+++ b/app/views/foreman_discovery/redhat_kexec.erb
@@ -44,7 +44,7 @@ Please read kexec(8) man page for more information about semantics.
   "initram": "<%= @kexec_initrd %>",
 <% if (@host.operatingsystem.name == 'Fedora' and @host.operatingsystem.major.to_i > 16) or
     (@host.operatingsystem.name != 'Fedora' and @host.operatingsystem.major.to_i >= 7) -%>
-  "append": "ks=<%= foreman_url('provision') + "&static=yes" %> inst.ks.sendmac <%= "ip=#{ip}::#{gw}:#{mask}:::none nameserver=#{dns} ksdevice=bootif BOOTIF=#{bootif} nomodeset #{append}" %>",
+  "append": "ks=<%= foreman_url('provision') + "&static=yes" %> inst.ks.sendmac <%= "ip=#{ip}::#{gw}:#{mask}:::none nameserver=#{dns} ksdevice=bootif BOOTIF=#{bootif} nomodeset " + options.compact.join(' ') %>",
 <% else -%>
   "append": "ks=<%= foreman_url('provision') + "&static=yes" %> kssendmac nicdelay=5 <%= "ip=#{ip} netmask=#{mask} gateway=#{gw} dns=#{dns} ksdevice=#{mac} BOOTIF=#{bootif} " + options.compact.join(' ') %>",
 <% end -%>
```

Thanks

**Comment by timogoebel** [comment]
@lzap: Done.

**Review by lzap — APPROVED** [review]
Tests are all red, this change is good tho.

**Pull request merged**
