### PR TITLE
Fixes #16324 - kexec templates work under safemode

### PR DESCRIPTION
**Pull request by lzap**
Easy one.

### CODE REVIEW

**Comment by lzap** [comment]
@dLobatog when this is merged I will do new nightly build, regression :-(

**Comment by lzap** [comment]
Since @dLobatog will be busy later this week, mind taking a look @orrabin ? Quick and easy merge. Context: `@kernel, @initrd` wont work in safe mode, plus I renamed them because when doing template preview, these names are already used and gets overwritten.

**Comment by orrabin** [comment]
I tested this but needed https://github.com/theforeman/foreman/pull/3783 to actually get to the point that uses the template for that.
Since this is broken anyway I'll merge it now and it's affect will be noticeable after core pr is merged.

**Comment by orrabin** [comment]
merges as 78261c3e7da85a14bea5100ef7987c01e7149694, thanks @lzap!

**Pull request closed without merging**
