### PR TITLE
Fixes #33231 - update documentation link helper

### PR DESCRIPTION
**Pull request by lzap**
SSIA

This patch is going to be backported into 17.0 for Satellite 6.10.

### CODE REVIEW

**Comment by ShimShtein** [comment]
Didn't test it, but the code looks good. This will enable proper downstream branding.

**Comment by lzap** [comment]
Yeah thanks, this is for https://bugzilla.redhat.com/show_bug.cgi?id=1974687 

Once tests are green I am merging and pushing out a minor release for 6.10.

**Comment by lzap** [comment]
6394f2f..1f7af10  17.0-stable -> 17.0-stable

**Comment by lzap** [comment]
Pushed 17.0.3

**Pull request merged**
