### PR TITLE
make hostname and fact_column arrays

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ezr-ondrej would you mind looking at this? is this the right way to migrate settings to a different "type"?

**Review by ekohl — APPROVED** [review]
This looks sensible to me.

**Comment by ehelms** [comment]
@stejskalleos Could you double check over this if ready to merge?

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, works as expected

* `discovery_hostname` & `discovery_fact_column` settings are applied correctly
* Migration works well too, although having rollback option would be nice
* Tests & Rubocop are passing

**Comment by stejskalleos** [comment]
Thanks @everybody!

**Pull request merged**
