### PR TITLE
fixes #24148 - use new template renderer

### PR DESCRIPTION
**Pull request by timogoebel**
This needs theforeman/foreman#5683.

### CODE REVIEW

**Comment by lzap** [comment]
Looks good, thanks!

**Comment by lzap** [comment]
This fixed issues with autoprovisioning:

```diff
diff --git a/app/controllers/concerns/foreman/controller/discovered_extensions.rb b/app/controllers/concerns/foreman/controller/discovered_extensions.rb
index 9fb5e2f..741d8e3 100644
--- a/app/controllers/concerns/foreman/controller/discovered_extensions.rb
+++ b/app/controllers/concerns/foreman/controller/discovered_extensions.rb
@@ -51,7 +51,9 @@ module Foreman::Controller::DiscoveredExtensions
     host.discovery_rule = rule
     # render hostname only when all other fields are set
     original_name = host.name
-    host.name = host.render_template(rule.hostname) unless rule.hostname.empty?
+    source = Foreman::Renderer::Source::String.new(name: 'Hostname template', content: rule.hostname)
+    scope = Foreman::Renderer.get_scope(host: host)
+    host.name = Foreman::Renderer.render(source, scope)
     # fallback to the original if template did not expand
     host.name = original_name if host.name.empty?
     # explicitly set all inheritable attributes from hostgroup
diff --git a/app/models/host/discovered.rb b/app/models/host/discovered.rb
index 2fbff87..73c4b89 100644
--- a/app/models/host/discovered.rb
+++ b/app/models/host/discovered.rb
@@ -183,7 +183,7 @@ class Host::Discovered < ::Host::Base
       template_name = Setting["discovery_#{kind.downcase}_lock_template"]
       Rails.logger.info "Locking discovered host #{self.mac} in subnet #{subnet} via #{template_name} template"
       template = ::ProvisioningTemplate.find_by_name(template_name)
-      rendered_template = render_template(template: template, subjects: { host: self })
+      rendered_template = render_template(template: template, params: { host: self })
       subnet.tftp_proxy.set(kind, mac, :pxeconfig => rendered_template)
     end
   rescue ::Foreman::Exception => e
diff --git a/test/unit/discovered_extensions_test.rb b/test/unit/discovered_extensions_test.rb
index b7c3a0e..96f1e01 100644
--- a/test/unit/discovered_extensions_test.rb
+++ b/test/unit/discovered_extensions_test.rb
@@ -157,7 +157,9 @@ class DiscoveredExtensionsTest < ActiveSupport::TestCase
     r1 = FactoryBot.create(:discovery_rule, :priority => 1, :search => "facts.somefact = abc", :organizations => [host.organization], :locations => [host.location], :hostgroup => hostgroup)
     host.primary_interface.expects(:queue_tftp).at_least(1)
     host.primary_interface.expects(:queue_dhcp).at_least(1)
-    assert managed_host = perform_auto_provision(host, r1)
+    managed_host = perform_auto_provision(host, r1)
+    assert_empty host.errors
+    assert managed_host
     assert_empty managed_host.errors
     refute_nil hostgroup.pxe_loader, managed_host.pxe_loader
     assert_equal hostgroup.pxe_loader, managed_host.pxe_loader
@@ -187,7 +189,9 @@ class DiscoveredExtensionsTest < ActiveSupport::TestCase
     r1 = FactoryBot.create(:discovery_rule, :priority => 1, :search => "facts.somefact = abc", :organizations => [host.organization], :locations => [host.location], :hostgroup => hostgroup)
     host.primary_interface.expects(:queue_tftp).at_least(1)
     host.primary_interface.expects(:queue_dhcp).at_least(1)
-    assert managed_host = perform_auto_provision(host, r1)
+    managed_host = perform_auto_provision(host, r1)
+    assert_empty host.errors
+    assert managed_host
     assert_empty managed_host.errors
     refute_nil hostgroup.pxe_loader, managed_host.pxe_loader
     assert_equal hostgroup.pxe_loader, managed_host.pxe_loader
```

Tests are failing locally for me and this is irrelevant - develop is broken: http://ci.theforeman.org/job/test_plugin_matrix/5684/

**Comment by timogoebel** [comment]
Thanks, @lzap. Amended your code to the PR.

**Comment by lzap** [comment]
Thanks, let's just wait until core is merged and then we can retest.

**Comment by lzap** [comment]
I am back! Hello! [test]

**Comment by lzap** [comment]
Develop is broken due to media changes, I am going to merge this one.

**Pull request merged**
