### PR TITLE
Fixes #9015 - Use number_f for priority and max_count

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by dLobatog** [comment]
👍 at first glance, will merge in a bit. Thanks @orrabin !

**Comment by lzap** [comment]
Yeah wfm. Any idea what's wrong with Jenkins? Have we dropped 1.9.3 support?

**Comment by lzap** [comment]
Hmm looks like all Postgres tests failed. Running locally.

**Comment by dLobatog** [comment]
Thanks @orrabin & @lzap !

**Pull request merged**
