### PR TITLE
Fixes #35127 - migrate discovery templates to Foreman

### PR DESCRIPTION
**Pull request by nofaralfasi**
Related to this [PR](https://github.com/theforeman/foreman/pull/9314) on Foreman.
This PR applies a more complex solution for the missing description issue (compared to this [PR](https://github.com/theforeman/foreman_discovery/pull/580)), and it is intended for Satellite 6.13.

### CODE REVIEW

**Comment by nofaralfasi** [comment]
Working on solving the failing tests.

**Review by stejskalleos — CHANGES_REQUESTED** [review]
Two things:
* We should also remove `template_labels 'kexec' => N_('Discovery Kexec template')` from `lib/foreman_discovery/engine.rb`
* Test `test/unit/managed_extensions_test.rb` is failing because of removed template here: https://github.com/theforeman/foreman_discovery/blob/develop/test/unit/managed_extensions_test.rb#L13 Fix is simple: put the removed template to the `test/fixtures` and load it from there

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**

**Comment by stejskalleos** [comment]
Thanks @nofaralfasi !

**Pull request merged**
