### PR TITLE
Fixes #29482 - favor update over update_attributes

### PR DESCRIPTION
**Pull request by ezr-ondrej**
`update_attributes` got deprecated in Rails 6.0

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Let's wait for #498 and fix theese by rubocop.

**Comment by mmoll** [comment]
[test foreman_discovery]

**Comment by mmoll** [comment]
Fixes at least the `update_attributes` related Rails 6 test fialures, so I'd vote to merge this merge now and look into the remaining problems.

**Review by timogoebel — APPROVED** [review]

**Comment by lzap** [comment]
Isn't this a semantic change?

https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute

This is the fastest way to update attributes because it goes straight to the database, but take into account that in consequence the regular update procedures are totally bypassed. In particular: Validations are skipped. Callbacks are skipped.

But.

https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update

Updates the attributes of the model from the passed-in hash and saves the record, all wrapped in a transaction. If the object is invalid, the saving will fail and false will be returned.

**Review by lzap — APPROVED** [review]
Ondra explained to me that I actually thought `update_columns`. Yeah, let's unblock this.

**Comment by mmoll** [comment]
@lzap it's `update_attributes` with an s at the end ;)

**Comment by lzap** [comment]
For the record, these guys are failing:

```
    OrgAdminJSTest::user is org admin of two organizations through single role.test_org_admins_of_two_orgs_can_work_with_resources_in_their_organizations
    Api::V2::DiscoveryRulesControllerTest.test_0001_should get index
    Api::V2::DiscoveryRulesControllerTest.test_0002_should search discovery rule
    Api::V2::DiscoveryRulesControllerTest.test_0003_should show discovery rule with taxonomy
```

**Comment by lzap** [comment]
I can fix the discovery rules easily:

```
Failure:
Api::V2::DiscoveryRulesControllerTest#test_0003_should show discovery rule with taxonomy [/home/lzap/work/foreman_discovery/test/functional/api/v2/discovery_rules_controller_test.rb:28]:
Expected response to be a <2XX: success>, but was a <500: Internal Server Error>
Response body: {
  "error": {"message":"undefined local variable or method `implicit_order_column' for #<ActiveRecord::Associations::CollectionProxy []>"}
}
```

Not sure about that JS one, I don't see it locally.

**Comment by mmoll** [comment]
@lzap The JS test was transient. Rails 5 is green and Rails 6 failing with the three errors you listed above: https://ci.theforeman.org/job/test_plugin_matrix/1950/

**Pull request merged**
