### PR TITLE
fixes #11313 -Add the app/views path to rabl view path of foreman

### PR DESCRIPTION
**Pull request by phirince**
I screwed up the previous pull request. Submitting a fresh one now.

-PP

### CODE REVIEW

**Comment by lzap** [comment]
Can you amend once again in this form, there was a space missing:

```
Fixes #11313 - Add the app/views path to RABL view path of foreman
```

**Comment by phirince** [comment]
Can I do anything to speed up the review process? I have squashed the commits to a single commit and made sure the commit message is of the proper form.

Thanks,
-PP

**Comment by orrabin** [comment]
[test]

**Comment by phirince** [comment]
Please note that this is a resubmission of https://github.com/theforeman/foreman_discovery/pull/205.

-PP

**Comment by domcleal** [comment]
Looks fine to me.

**Comment by orrabin** [comment]
merged as e31a50d635041b67063cc46b5be061ace03d93a3 thanks @phirince!

**Pull request closed without merging**
