### PR TITLE
add API route to rename hostname without triggering conversion to ManagedHost

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
This feature is needed for the stand-alone [fusor-server](https://github.com/fusor/fusor-server) project that only uses API's and doesn't use a foreman plugin to extend models or controllers.

**Comment by lzap** [comment]
Thanks, we need a test for this.

**Comment by lzap** [comment]
@isratrade if you want this in 1.15 (which is a milestone release) push today please.

**Comment by isratrade** [comment]
@lzap, this PR is no longer needed for the [fusor](https://github.com/fusor/fusor-ember-cli/) project I was working in. If you still feel it is worthwhile to the community, I will write a test.

**Comment by lzap** [comment]
Thanks that'd be helpful if you can get to this. Just one positive integration test is fine.

**Comment by ohadlevy** [comment]
@lzap which usage case does this solve? Can't we always do a put and change the name?

**Comment by lzap** [comment]
We can, closing.

**Pull request closed without merging**
