### PR TITLE
Fixes #9963 - removed unused permissions and role

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
You can use https://github.com/lzap/foreman-dev-dbs to try to reproduce. But I was not able to get into that state. Tested on artifically created roles/permissions.

**Comment by orrabin** [comment]
[test]

**Comment by lzap** [comment]
Late on mails, ping me directly if you need an action.

**Comment by lzap** [comment]
Ping?

**Comment by orrabin** [comment]
merged as 46f4aee0ff2b078fb11d67cac7f39ececa3f9ab3, thanks @lzap!

**Pull request closed without merging**
