### PR TITLE
Fixes #31203 - welcome page for discovery rules

### PR DESCRIPTION
**Pull request by rabajaj0509**
Tasks involved in this effort are as follows:

* [x]  Adding button for the `Create Discovery Rule`
* [x]  Suitable icon for Discovery Rules
* [x]  Suitable description for Discovery Rules
* [x]  Add test cases for welcome page

RulesPage

Apart from this, what do you think @laviro?

### CODE REVIEW

**Comment by rabajaj0509** [comment]
We are still using the server to display the welcome page, soon we will use the react router to perform the routes and then we will not use the `welcome` method and the rails magic :stuck_out_tongue: It will make the loading of the pages very quick.

@laviro can you take a look at this PR? @lzap on your local we can compile the webpack in the test environemnt, something like `bundle exec rake webpack:compile  RAILS_ENV=test` and it should work fine :smile:

**Review by lzap — APPROVED** [review]
It works on my instance. @laviro to review the code thanks.

**Review by Ron-Lavi — APPROVED** [review]
Code wise looks good to me, didn't test it out yet

**Comment by lzap** [comment]
Thanks all! Merged.

**Pull request merged**
