### PR TITLE
Fixes #10781 - fixed unit tests for new partition tables

### PR DESCRIPTION
**Pull request by lzap**
This will _fail_. It either needs this patch in core

https://github.com/theforeman/foreman/pull/2451

or incorporating the FG block in the plugin.

### CODE REVIEW

**Comment by lzap** [comment]
Also added some extra asserts to have better failure reports.

**Comment by orrabin** [comment]
I tested this and all tests past when using https://github.com/theforeman/foreman/pull/2451.
I'll merge this after the core patch is merged unless you want to add `FactoryGirl.create` to everything you need in os

**Comment by lzap** [comment]
Ok core merged, [test]

**Comment by lzap** [comment]
Tests look stuck, local run maybe?

**Comment by stbenjam** [comment]
Don't think it can run automatically until the test is green.

I kicked off a manual test here:
  http://ci.theforeman.org/view/Plugins/job/test_plugin_pull_request/911/

Hope I got the parameters right, we'll see!

**Comment by stbenjam** [comment]
Tests are :green_heart:

Merged as 2bb19c23490a4672474571b5b0e5091ce44a04d5, thanks @lzap!

**Comment by lzap** [comment]
Thank you _so much_! :-) :beer:

**Pull request closed without merging**
