### PR TITLE
Fixes #11732 - added Discovered/Associated host search buttons

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
Two new buttons that allows searching for associated hosts:

image

image

**Comment by lzap** [comment]
[test]

**Comment by orrabin** [comment]
@lzap this needs rebasing

**Comment by lzap** [comment]
Done!

**Comment by dLobatog** [comment]
Merged as 2677405fd0c548c8833e51d916902b0fae696ae5 , thanks @lzap!

**Pull request closed without merging**
