### PR TITLE
Fixes #13829 - view hosts permission added to reader

### PR DESCRIPTION
**Pull request by lzap**
SSIA, see the linked BZ for details. I am _not_ adding a seed script to add
this permission to existing roles for security reasons - users must explicitly
add this permission if they need it.

### CODE REVIEW

**Comment by lzap** [comment]
There are 5 patches ready for review/merge before I close 5.0.2 release. Can you take a look @orrabin please?

**Comment by lzap** [comment]
I've doublechecked, for new installation the permission is present. I rebased - cleaned the section a bit and added few comments.

**Comment by orrabin** [comment]
Test failure is unrelated - I tested this with a new installation and an existing one before and after deleting the role and it works as expected for each case.

**Comment by orrabin** [comment]
merged as ee63dc3c74e7e799de43896dc199ea0c7324aa5e, thanks @lzap!

**Pull request closed without merging**
