### PR TITLE
Refs #9044 - disabled MAC validation test for 1.7

### PR DESCRIPTION
**Pull request by lzap**
This goes into _2.0-stable_ only!

### CODE REVIEW

**Comment by domcleal** [comment]
http://ci.theforeman.org/job/test_plugin_pull_request/493/ is :white_check_mark:

**Comment by lzap** [comment]
Thank you, appreciated.

**Comment by GregSutcliffe** [comment]
merged, thanks!

**Comment by lzap** [comment]
Merged as c64eb1585ebde9adcd8ada958179eaa2d78769fa for the record, thank you.

**Pull request closed without merging**
