### PR TITLE
Fixes #25880 - more explicit only fields

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
LGTM

**Review by ares — APPROVED** [review]

**Comment by lzap** [comment]
Rebased, RTM? Thanks.

**Comment by ares** [comment]
are test failures expected here?

**Comment by ares** [comment]
oh sorry, they are only on ruby 2.4 so I guess unrelated, thanks @lzap, merging!

**Pull request merged**
