### PR TITLE
Fixes #24880 - VLAN provisioning support

### PR DESCRIPTION
**Pull request by lzap**
Test for https://github.com/theforeman/foreman/pull/5989

### CODE REVIEW

**Comment by lzap** [comment]
Can I get a quick merge if that's green? @timogoebel ty.

**Comment by timogoebel** [comment]
Sure. Unfortunately, tests are 🔴 .

**Comment by lzap** [comment]
Core fixed. [test foreman_discovery]

**Comment by lzap** [comment]
All good Timo! Yay.

**Comment by timogoebel** [comment]
Thanks!

**Pull request merged**
