### PR TITLE
Fixes #15368 - refresh existing discovered host

### PR DESCRIPTION
**Pull request by lzap**
Existing host (when renamed) was ignored.

Also fixed 404 for show page.

Replaces https://github.com/theforeman/foreman_discovery/pull/275

### CODE REVIEW

**Comment by cfchase** [comment]
Tested code against Sat 6.2 branch.  Verified it refreshes facts and no longer duplicates the renamed discovered host.

**Comment by lzap** [comment]
> Tested code against Sat 6.2 branch.  Verified it refreshes facts and no longer duplicates the renamed discovered host.

Thanks, will take sometime until it lands z-stream, I suggest you to
patch the package yourself.

## 

Later,
 Lukas #lzap Zapletal

**Comment by orrabin** [comment]
Tested against develop and it looks good.

**Comment by dLobatog** [comment]
Merged as 7dc5b8d48a7fd09766e5ecdb667ab77a02956f7b, thanks @lzap!

**Pull request closed without merging**
