### PR TITLE
Fixes #9076 - fix two-pane in edit discovery rule

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by orrabin** [comment]
[test]

**Comment by lzap** [comment]
Merged the unit test fix, let's re [test].

Is this going to be merged into 2.0 stable branch?

**Comment by orrabin** [comment]
@lzap this can go into 2.0 stable, it will be disregarded in 1.7 and work in 1.8 so no conflicts.

**Comment by lzap** [comment]
Just to be perfectly clear - you mean this should go both into develop branch and stable branch?

**Comment by orrabin** [comment]
@lzap if you want the stable branch to work with 1.8 then yes

**Comment by lzap** [comment]
Merged as 5efc7a1, thank you.

**Pull request closed without merging**
