### PR TITLE
Add Puppet params with puppet plugin

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Needs https://github.com/theforeman/foreman_puppet/pull/211

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
@lzap could you test this? Puppet side is done in `foreman_puppet 1.0.4`

**Comment by ezr-ondrej** [comment]
@lzap ping?

**Comment by lzap** [comment]
There is no error, however, when I set environment it is not saved. The provisioned host has `nil` for environment.

**Comment by ezr-ondrej** [comment]
I believe it works now

**Comment by lzap** [comment]
Works with customization form, without and also with env override. THANK YOU!

**Pull request merged**
