### PR TITLE
Refs #23060 - Refactor Reboot All and Auto Provision All

### PR DESCRIPTION
**Pull request by ik5**
One important note: I was unable to figure out yet how to enable the drop down if no item was selected.

### CODE REVIEW

**Comment by ik5** [comment]
Before:
original discovered host reboot provision all buttons

After:
new discovered host reboot provision all buttons

**Comment by rabajaj0509** [comment]
Thanks @ik5, I guess I have a better solution for this issue, only the tests are failing which I am not being able to fix. Would you mind having a look at https://github.com/theforeman/foreman_discovery/pull/364/files ? It will be great if we can fix that, the code works just fine but the tests are a little tricky to get away with :)

**Comment by ik5** [comment]
@rahulbajaj0509 sure, I'll take a look and see how I can help :)

**Comment by lzap** [comment]
I merged https://github.com/theforeman/foreman_discovery/commit/2c5cbe1724da5a76e6ab9c9d0cd943e91768c9df today which actually move this to the correct place. I am going to close this now. Thanks!

**Pull request closed without merging**
