### PR TITLE
Fixes #20170 - Fix the UI for delete modal

### PR DESCRIPTION
**Pull request by rabajaj0509**

### CODE REVIEW

**Review by ohadlevy — COMMENTED** [review]
Thanks, can you please provide a before/after screenshot?

**Comment by dLobatog** [comment]
[test]

**Comment by rabajaj0509** [comment]
Before :  
delete_modal

After:
deletemodalfix

**Comment by rabajaj0509** [comment]
i guess, this looks good but as the number of entries will increase the 'organization' might collide with the submit button. Can someone give a feedback on this ?

**Review by dLobatog — APPROVED** [review]
@rahulbajaj0509 If try to delete many, the modal will become larger but it will not collide with the Submit button. You can reproduce the situation already in the Hosts page, trying to remove many hosts at the same time.

**Comment by dLobatog** [comment]
Thanks @rahulbajaj0509 !

**Comment by Rohoover** [comment]
Can we use the Inline messaging warning instead of the current style? The current style doesn't really exist anywhere else with any consistency. 

http://www.patternfly.org/pattern-library/communication/inline-notifications/

**Comment by rabajaj0509** [comment]
@Rohoover thanks for the input, would surely make the changes and raise a pr :)

**Pull request merged**
