### PR TITLE
Fix wrong IP address fact name

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by lzap** [comment]
I can confirm that :ip does not work when uploading facts and :ipaddress is present.

It does not work when I do Refresh facts tho. Testing.

**Comment by lzap** [comment]
Got that, can you change it to

```
facts['ipaddress']
```

Then :+1:

**Comment by ares** [comment]
Fixed

**Comment by lzap** [comment]
Can you add

```
Refs #6925 ...
```

to the commit message? https://github.com/theforeman/foreman_discovery/pull/80 Thanks!

**Comment by lzap** [comment]
Fixed the commit message and merged as b4220a2 Refs #6925 - Fix wrong IP address fact name <Marek Hulan>

**Pull request closed without merging**
