### PR TITLE
Fixes #29531 - enable Rubocop 0.80

### PR DESCRIPTION
**Pull request by ezr-ondrej**
:policeman: doesn't like what he see :disappointed:

### CODE REVIEW

**Comment by mmoll** [comment]
https://ci.theforeman.org/job/test_plugin_matrix/1929/ - how the heck does that work in this PR? :astonished:

**Comment by ezr-ondrej** [comment]
> https://ci.theforeman.org/job/test_plugin_matrix/1929/ - how the heck does that work in this PR?

I'm missing what we are talking :thinking: there is just one unrelated error. The rubocop doesn't even ran, right?

**Comment by mmoll** [comment]
> I'm missing what we are talking thinking there is just one unrelated error.

Yes, that test is failing since months

> The rubocop doesn't even ran, right?

Exactly, because the Jenkins run already ends with that failed test.

**Comment by ezr-ondrej** [comment]
> Exactly, because the Jenkins run already ends with that failed test.

I don't think rubocop ever run on this repo. There was no real point to it while it was checking only rabl templates anyways.

**Comment by mmoll** [comment]
GH-491 should IMHO go in first, as it disables the vast majority of non-Rails cops.

**Comment by ezr-ondrej** [comment]
> [GH-491](https://github.com/theforeman/foreman_discovery/pull/491) should IMHO go in first, as it disables the vast majority of non-Rails cops.

Well, it disables almost all the cops! I don't like it xD

**Comment by lzap** [comment]
Do you think this JS test fail due to changes in core?

**Comment by lzap** [comment]
Can you disable all I want to disable here:

https://github.com/theforeman/foreman_discovery/pull/491/files

**Comment by lzap** [comment]
I closed the other PR, let's finish this one instead it looks better.

**Comment by ezr-ondrej** [comment]
I've disabled all the cops, that are disabled in core :thinking: what about that?

**Comment by lzap** [comment]
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
Inspecting 74 files
..........................................................................

74 files inspected, no offenses detected

```

**Review by lzap — APPROVED** [review]

**Pull request merged**
