### PR TITLE
Fixes #23793 - Port robottelo tests for settings

### PR DESCRIPTION
**Pull request by odovzhenko**
Port robottelo tier1 tests for settings

Related Robottelo issue: SatelliteQE/robottelo#5978

Part of robottelo minitest port project: https://github.com/SatelliteQE/robottelo/projects/1

Also contains updates for obsolete configuration found in  .rubocop_todo.yml

### CODE REVIEW

**Comment by odovzhenko** [comment]
@ares @mmoll Could you please review?

**Comment by mmoll** [comment]
[test foreman_discovery]

**Comment by mmoll** [comment]
@odovzhenko Please rebase, that should at least fix the `ReferenceError: Can't find variable: jQuery` errors.

**Comment by odovzhenko** [comment]
@mmoll Rebased, all tests passed.

**Comment by rabajaj0509** [comment]
LGTM :)

**Comment by ares** [comment]
LGTM too, cops could have been updated in separate commit but I don't think it's a big deal. Merging, thanks @odovzhenko

**Pull request merged**
