### PR TITLE
Fixed #22941 - better error with filters

### PR DESCRIPTION
**Pull request by lzap**
Just better errors. There is a helper script update as well.

Develop is currently blocked, we are working on it in

https://github.com/theforeman/foreman_discovery/pull/413

### CODE REVIEW

**Comment by lzap** [comment]
Develop is now green again, please rebase thanks!

**Comment by lzap** [comment]
Added one fix for failing tests @rahulbajaj0509 is it green locally for you?

**Comment by lzap** [comment]
Develop tests are not passing, this is locally green so I am gonna merge this to unblock develop. We have many PRs to move on.

**Comment by rabajaj0509** [comment]
@lzap yes, it was green for me as well. Sorry, had seen your reply, tested it and thought I had replied to it.

**Pull request merged**
