### PR TITLE
Fixed 500 error on reboot

### PR DESCRIPTION
**Pull request by lzap**
This should be our final 0.3.0 version if no bugs are found.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Seems sensible, is there a debug image I can download or shall iI build one?

**Comment by GregSutcliffe** [comment]
Nvm, i see the -dev post. Will test.

**Comment by lzap** [comment]
Yup the 0.3.0 version there, although I see I forgot to change version number in the patch. Adding.

**Comment by mmoll** [comment]
I can confirm, that the 500 error on reboot is fixed. :+1:

**Comment by GregSutcliffe** [comment]
Merged as 441ac0978b75c42d3b6121b92f7cbc03cbeae2f3, thanks @lzap

**Pull request closed without merging**
