### PR TITLE
Fixes #19051 - Prevent N+1 on FactValue index

### PR DESCRIPTION
**Pull request by tbrisker**
This depends on changes in https://github.com/theforeman/foreman/pull/4390 - test should fail until that gets merged.

### CODE REVIEW

**Comment by lzap** [comment]
But they dont! :-)

**Comment by tbrisker** [comment]
That's odd... That means the tests in https://github.com/theforeman/foreman_discovery/commit/f91555774b4856492ffa262a12749882906217bc don't really check that correctly

**Comment by lzap** [comment]
Why this should pass only when CSV was merged, I don't see any link between the two. Can you explain to me?

**Comment by tbrisker** [comment]
@lzap there was a change in a previous version of that PR that moved facts from `Host::Managed` to `Host::Base` which would make this workaround redundant, but that led to other issues with permissions and searching so I took it out for now. 
I am curious as to why the tests pass with this change, maybe @dLobatog has an idea since he created the original workaround?

**Comment by lzap** [comment]
Found it, please change this line

    assert fact_value.discovered_host, fact_value.host

to

    assert_equal fact_value.discovered_host, fact_value.host

(or better assert_nil)

Then it will fail. Can you push the change to see if it works, the patch was merged an hour ago.

**Comment by tbrisker** [comment]
Pushed again with a corrected test. This test should now fail until fix is done in core.

**Comment by lzap** [comment]
Does not work with the patch merged in core... We should consider doing our own facts rather than using Puppet Facts.

**Comment by lzap** [comment]
I believe this is related too: https://github.com/theforeman/foreman/pull/3724

**Comment by lzap** [comment]
I filed new PR in core which changes FactValue belonging to Host::Base rather than Host::Managed. This will enable discovery to drop the extra association that is undeeded. https://github.com/theforeman/foreman/pull/4434

**Comment by lzap** [comment]
I will leave this opened for now, release discovery and then get back to this. But I believe this can't be easily fixed for now.

**Comment by tbrisker** [comment]
Opened another attempt at fixing this in core which will hopefully make this PR work as well.

**Comment by lzap** [comment]
Thanks, core looks good but this is not it, we need to simply drop `discovered_host` association and go with normal `host` association. That's the proper way to fix this. Easy change, the only challenge is to get migration right so existing host associations are changed accordingly. Do you want to work on this? Otherwise I will pick it up next week.

**Comment by lzap** [comment]
Replaced by https://github.com/theforeman/foreman_discovery/pull/339

**Pull request closed without merging**
