### PR TITLE
Fixes #21153 - Passing conditions to destroy_all is deprecated

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
this is compatible with Rails 4.2

**Comment by lzap** [comment]
We can hopefully [test] now.

**Comment by mmoll** [comment]
Not yet. But Rails 4 in develop is green now. After merging this, the 22 failures with Rails 5 will come down to about 6, which will need more analysis.

**Comment by lzap** [comment]
Thanks.

**Pull request merged**
