### PR TITLE
Refs #9162 - removed compatibility workarounds

### PR DESCRIPTION
**Pull request by lzap**
This replaces the incorrect PR
https://github.com/theforeman/foreman_discovery/pull/146

(I issued from incorrect local branch).

Also dropped the `unless` block, you were right @domcleal

### CODE REVIEW

**Comment by domcleal** [comment]
Looks correct to me now.  The Gem::Version stuff isn't required, but is presumably harmless.

**Comment by domcleal** [comment]
Hey, and stable tests work!

**Comment by lzap** [comment]
Since you guys are on the way to FOSDEM and I want to prepare for rc2 today, I am merging this myself.

**Comment by lzap** [comment]
Ok I noticed Greg pushed it already. Was not aware of that, thanks. For the record: 931620152295dd6b721b55892143a1527694aa51

**Pull request closed without merging**
