### PR TITLE
fixes #10554 - remove the UI route for creating a discovered host.

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by orrabin** [comment]
@ohadlevy the title says 'non UI route' but you are removing the UI route.

**Comment by ohadlevy** [comment]
@orrabin effectively i'm removing the non ui (e.g json format) from the ui controllers leaving only the ability to use the api controllers or the actions that are visible in the ui.
how would you want me to rephrase ?

**Comment by ohadlevy** [comment]
@orrabin scratch that, I mixed it up with #187.

this removes methods that are not really used by the discovery image anymore.
so, since its not visible in the UI, I'm removing it from the code?

**Comment by lzap** [comment]
Thanks, will do during our cleanup round.

**Comment by lzap** [comment]
Merged as 1f30d55ff87cb2a04b421a2b119275d40e268411, thank you!

**Pull request closed without merging**
