### PR TITLE
Refs #9597 - adding a test to check that token is not created for dis…

### PR DESCRIPTION
**Pull request by orrabin**
…covered host

### CODE REVIEW

**Comment by orrabin** [comment]
this will fail until https://github.com/theforeman/foreman/pull/2390 is merged

**Comment by lzap** [comment]
Tested, green once the core fix is merged.

**Comment by orrabin** [comment]
[test]

**Comment by lzap** [comment]
[test]

**Comment by lzap** [comment]
Merged as c864794a478775bd4703dd2631495150659a2209, thank you!

**Pull request closed without merging**
