### PR TITLE
Fixes #27499 - fixed primary bond/bridge tests

### PR DESCRIPTION
**Pull request by lzap**
This should fix some tests due change https://github.com/theforeman/foreman/pull/6933

However it does not change all of them, two more are failing. It looks like this broke LLDP auto bonder which we added last year and I struggle to understand why.

```
Failure:
HostDiscoveredTest#test_0042_provision_interface is switched to bond0 with more than one interface on the same VLAN [/home/lzap/work/foreman_discovery/test/unit/host_discovered_test.rb:473]:
Expected: "bond0"
  Actual: "br180"

Failure:
HostDiscoveredTest#test_0044_former provision_interface is cleanup up after switching to bond0 [/home/lzap/work/foreman_discovery/test/unit/host_discovered_test.rb:497]:
Expected "10.35.27.3" to be nil.
```

### CODE REVIEW

**Comment by lzap** [comment]
@timogoebel any idea why the two tests fail now? https://github.com/theforeman/foreman_discovery/pull/439

**Comment by timogoebel** [comment]
@lzap: The fact fixtures are garbage, if we remove the bridge interface (which was ignored by mistake prior to the fix in core), the tests pass (locally).

```diff
diff --git a/test/facts/facts_with_lldp_bond_candidate.json b/test/facts/facts_with_lldp_bond_candidate.json
index de540d9..b7dbba9 100644
--- a/test/facts/facts_with_lldp_bond_candidate.json
+++ b/test/facts/facts_with_lldp_bond_candidate.json
@@ -6,14 +6,11 @@
     "kernelmajversion": "2.6",
     "kernelversion": "2.6.32",
     "macaddress_vnet0": "FE:54:00:1E:45:13",
-    "macaddress_br181": "E4:1F:13:CC:36:58",
     "macaddress_usb0": "E6:1F:13:D0:43:A3",
     "macaddress_vnet1": "FE:54:00:45:E5:3E",
     "rubysitedir": "/usr/lib/ruby/site_ruby/1.8",
-    "macaddress_br182": "E4:1F:13:CC:36:58",
     "processor4": "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz",
     "macaddress_vnet2": "FE:54:00:93:F5:56",
-    "macaddress_br183": "E4:1F:13:CC:36:58",
     "ps": "ps -ef",
     "processor5": "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz",
     "macaddress_vnet10": "FE:54:00:7D:F8:24",
@@ -28,16 +25,15 @@
     "macaddress_vnet4": "FE:54:00:62:53:67",
     "hostname": "h02",
     "osfamily": "RedHat",
-    "gateway_if": "br180",
+    "gateway_if": "eth0",
     "lsbrelease": ":core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch",
     "kernelrelease": "2.6.32-131.12.1.el6.x86_64",
     "kernel": "Linux",
     "facterversion": "1.6.2",
     "uptime_seconds": "13651752",
     "macaddress_vnet5": "FE:54:00:01:B9:9C",
-    "interfaces": "br180,br181,br182,br183,eth0,eth0_181,eth0_182,eth0_183,eth1,lo,usb0,vnet0,vnet1,vnet2,vnet3,vnet4,vnet5,vnet7,vnet10",
+    "interfaces": "eth0,eth0_181,eth0_182,eth0_183,eth1,lo,usb0,vnet0,vnet1,vnet2,vnet3,vnet4,vnet5,vnet7,vnet10",
     "macaddress_vnet7": "FE:54:00:D8:F9:38",
-    "netmask_br180": "255.255.255.192",
     "macaddress_eth0": "E4:1F:13:CC:36:58",
     "is_virtual": "false",
     "macaddress": "E4:1F:13:CC:36:58",
@@ -47,7 +43,6 @@
     "macaddress_eth1": "E4:1F:13:CC:36:5A",
     "timezone": "GMT",
     "fqdn": "a.server.b.domain",
-    "ipaddress_br180": "10.35.27.2",
     "ipaddress_eth0": "10.35.27.3",
     "ipaddress_eth1": "10.35.27.4",
     "puppetversion": "2.6.12",
@@ -69,12 +64,10 @@
     "network_lo": "127.0.0.0",
     "gateway": "10.35.27.62",
     "lsbdistid": "RedHatEnterpriseServer",
-    "network_br180": "10.35.27.0",
     "lsbdistdescription": "Red Hat Enterprise Linux Server release 6.2 (Santiago)",
     "swapsize": "17.70 GB",
     "processor0": "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz",
     "processor1": "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz",
-    "macaddress_br180": "E4:1F:13:CC:36:58",
     "selinux": "false",
     "domain": "server.b.domain",
     "architecture": "x86_64",
```

**Comment by lzap** [comment]
Yeah I accepted them unchanged because I don't have LLPD device and I did not want to mess around with them. I created a VM with a simple bond and added the JSON: `test/facts/bond0-eth0-eth1-active-passive.json` so at least I can discover those hosts easily with the `discover-host` fake script, but it does not have an LLPD facts.

**Comment by lzap** [comment]
Rebased, this is now green locally. Honestly I *hate* this autobond setting, discovery should have some good way of customizing interfaces via some scripting or something like that.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @lzap.

**Pull request merged**
