### PR TITLE
Fixes #19051 - Prevent N+1 on FactValue index

### PR DESCRIPTION
**Pull request by lzap**
The patch removes unnecessary `discovered_host` relation because now the `host` relation on `FactValue` is `Host::Base`. This simplifies things and also should fix N+1 problem. @tbrisker

Replaces https://github.com/theforeman/foreman_discovery/pull/337

Needed in core https://github.com/theforeman/foreman/pull/4441 (I am merging this right now)

### CODE REVIEW

**Comment by tbrisker** [comment]
I confirm this fixes the N+1 issue, but I can't merge here.

**Comment by tbrisker** [comment]
@lzap Looks like tests are now failing, mind taking a look?

**Comment by lzap** [comment]
It does work locally here just fine [test]

**Comment by lzap** [comment]
Passed, very strange @tbrisker ...

**Comment by tbrisker** [comment]
I guess it was some random failure, merging.

**Comment by tbrisker** [comment]
Thanks @lzap !

**Pull request merged**
