### PR TITLE
Fixes #15533 - Change from accessible_hostgroups to accessible_resour…

### PR DESCRIPTION
**Pull request by shlomizadok**
…ce_records

*\* Foreman >= 1.13

### CODE REVIEW

**Comment by shlomizadok** [comment]
Test failure seems un-related?

**Comment by dLobatog** [comment]
@shlomizadok It's pretty consistent, I can always reproduce it with this PR & foreman core develop, can you fix it here?

**Comment by lzap** [comment]
I prefer to merge this right away tomorrow if you don't mind. I also don't see any relevance.

**Comment by lzap** [comment]
I am bringing the plugin back to life, this is the first step.

**Comment by lzap** [comment]
Merged as 755b23aad215d5dddf90b7570a84f2bcb3de52f1, thank you!

**Pull request closed without merging**
