### PR TITLE
Check for jenkins:unit task to enhance

### PR DESCRIPTION
**Pull request by dLobatog**
Checking for jenkins:setup (a namespace) was not allowing this to run the tests, plus, the key task we have to check is jenkins:unit, which is the one we want to append our job.

### CODE REVIEW

**Comment by domcleal** [comment]
:+1: subject to green light.

**Comment by lzap** [comment]
Going to test that locally. Is the failure on Jenkins unrelated?

**Comment by domcleal** [comment]
@lzap no, it's entirely related.  Tests now run and are :x:

I'd suggest either, a) merging it and fixing them up later, b) asking @eLobato really nicely to look into it, or c) taking his fix into a second PR and fixing it up too.

**Comment by lzap** [comment]
I am fine with merging this as is and I can work on tests later this week to get them into the shape again.

**Comment by domcleal** [comment]
At a guess, I'd say s/hosts/search/ on https://github.com/theforeman/foreman_discovery/blob/develop/app/controllers/discovered_hosts_controller.rb#L23

**Comment by lzap** [comment]
Let me take a look right away.

**Comment by lzap** [comment]
@eLobato I can confirm what @domcleal said, can you replace that single word and rebase? we are good to go then.

**Comment by dLobatog** [comment]
@lzap Fixed, tests should run in a min..

**Comment by domcleal** [comment]
Looks like there are some 1.8 failures too: https://github.com/theforeman/foreman_discovery/blob/develop/test/unit/host_discovered_test.rb#L7

**Comment by dLobatog** [comment]
I'll run Rubocop to find where we need the `=>`

**Comment by dLobatog** [comment]
@lzap @domcleal Changed all hash syntax problems Rubocop found.

**Comment by lzap** [comment]
Nice, looks good! Let's wait.

**Comment by dLobatog** [comment]
:green_apple:

**Comment by lzap** [comment]
Thanks, pushed as:
- a1ef1fc Change to hash rockets to support 1.8.7 <Daniel Lobato García>
- 9d9f669 Check for jenkins:unit task to enhance <Daniel Lobato García>

**Pull request merged**
