### PR TITLE
Create .packit.yaml

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
@evgeni Packit is failing on `/var/tmp/rpm-tmp.zH2NOV: line 33: scl: command not found`

[See the logs](https://copr.fedorainfracloud.org/coprs/packit/theforeman-foreman_discovery-600/build/6017891/):
```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.zH2NOV
+ umask 022
+ cd /builddir/build/BUILD
+ scl enable '%{scl}' -
/var/tmp/rpm-tmp.zH2NOV: line 33: scl: command not found


RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.zH2NOV (%prep)
    Bad exit status from /var/tmp/rpm-tmp.zH2NOV (%prep)
Finish: rpmbuild rubygem-foreman_discovery-22.0.4-1.20230607140852088827.pr600.2.g60d7c1f.el8.src.rpm
Finish: build phase for rubygem-foreman_discovery-22.0.4-1.20230607140852088827.pr600.2.g60d7c1f.el8.src.rpm
INFO: chroot_scan: 3 files copied to /var/lib/copr-rpmbuild/results/chroot_scan
INFO: /var/lib/mock/centos-stream-8-x86_64-1686147010.385112/root/var/log/dnf.rpm.log
/var/lib/mock/centos-stream-8-x86_64-1686147010.385112/root/var/log/dnf.librepo.log
/var/lib/mock/centos-stream-8-x86_64-1686147010.385112/root/var/log/dnf.log
ERROR: Exception(/var/lib/copr-rpmbuild/results/rubygem-foreman_discovery-22.0.4-1.20230607140852088827.pr600.2.g60d7c1f.el8.src.rpm) Config(centos-stream-8-x86_64) 0 minutes 38 seconds
INFO: Results and/or logs in: /var/lib/copr-rpmbuild/results
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
INFO: unmounting tmpfs.
Finish: clean chroot
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M d4dd331b728a46698c246478e197dce7 -D /var/lib/mock/centos-stream-8-x86_64-1686147010.385112/root -a -u mockbuild --capability=cap_ipc_lock --rlimit=RLIMIT_NOFILE=10240 --capability=cap_ipc_lock --bind=/tmp/mock-resolv.hrhymd8l:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb  --target x86_64 --nodeps /builddir/build/SPECS/rubygem-foreman_discovery.spec
```

Do I miss some configuration in the `yaml` file?

**Comment by evgeni** [comment]
No you didn't. Packit has problems with building our old SCL-enabled specs.

We gotta regenerate the rpm spec from the latest template for discovery, dropping all the SCL cruft.

**Comment by stejskalleos** [comment]
Waiting for https://github.com/theforeman/foreman-packaging/pull/9508

**Comment by stejskalleos** [comment]
@nofaralfasi review please, foreman_discovary is failing everywhere, not related to this task.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
