### PR TITLE
Fixes #33699 - restore compatibility with vanilla Foreman

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by lzap** [comment]
Thanks the only concern I have:

* user installs Foreman without plugin
* permissions are created
* user installs Puppet plugin and restarts
* will it create the missing permissions?

**Comment by ezr-ondrej** [comment]
> * will it create the missing permissions?

Yup, it will (or it should at least if something doesn't go terribly wrong), we always check the permissions for roles, that allows you to edit them in the code without migrations.

**Comment by lzap** [comment]
Yeah it really looks like the code should handle this properly. Okay, merging, releasing new version.

**Comment by lzap** [comment]
Looks like it really works, it even deletes it:

```
Role.find_by_name("Discovery Manager").permissions.pluck(:name)
=> ["view_architectures",
 "view_domains",
 "view_hostgroups",
 "edit_hosts",
 "build_hosts",
 "auto_provision_discovered_hosts",
 "view_hosts",
 "create_hosts",
 "destroy_discovered_hosts",
 "edit_discovered_hosts",
 "provision_discovered_hosts",
 "view_discovered_hosts",
 "submit_discovered_hosts",
 "view_locations",
 "assign_locations",
 "view_media",
 "view_models",
 "view_operatingsystems",
 "view_organizations",
 "assign_organizations",
 "view_ptables",
 "view_provisioning_templates",
 "view_realms",
 "view_smart_proxies",
 "view_subnets",
 "edit_discovery_rules",
 "execute_discovery_rules",
 "destroy_discovery_rules",
 "view_discovery_rules",
 "create_discovery_rules"]
```

**Comment by lzap** [comment]
https://github.com/theforeman/foreman-packaging/pull/7170
https://github.com/theforeman/foreman-packaging/pull/7171

**Pull request merged**
