### PR TITLE
Fixes #31278 - make the plugin version available in production

### PR DESCRIPTION
**Pull request by Ron-Lavi**
continued from #516 
@rabajaj0509 @lzap I tested it on nightly,
basically, it will generate the following URL: https://theforeman.org/plugins/foreman_discovery/16.3/index.html

### CODE REVIEW

**Comment by lzap** [comment]
Would you mind creating a Rails view helper method that returns plugin version? This looks a bit dirty.

**Comment by Ron-Lavi** [comment]
Sure, maybe we can even return the whole `documentation_url` instead? from the same helper

**Comment by lzap** [comment]
Yeah something like that, at your preference.

**Comment by lzap** [comment]
Ok tests are timing out on Ruby 2.7, interesting it was supposed to be faster :-)

The node is quite slow and hitting the two hours limit: https://ci.theforeman.org/job/foreman_discovery-pull-request/126/database=postgresql,label=fast,ruby=2.7/testReport/(root)/

**Review by lzap — APPROVED** [review]
This could easily be plugin-global helper, but I am fine we can move it if its needed. Thank you!

**Comment by lzap** [comment]
@laviro is this all that's need to be done to fix nightly? May I proceed with releasing another version?

**Comment by Ron-Lavi** [comment]
yes, that should do the work :)
should I open a CP to 16.1-stable branch?

**Comment by lzap** [comment]
No need, I haven't branched yet. I will tag a new release now.

**Comment by lzap** [comment]
I had no idea version is now in `package.json` so I had to bump the release two times: https://rubygems.org/gems/foreman_discovery

foreman_discovery-16.3.4.gem it is.

**Comment by Ron-Lavi** [comment]
Cool, the package.json one is not used really as we are not publishing an npm, si it's more for beauty :P

**Comment by lzap** [comment]
* RPM: https://github.com/theforeman/foreman-packaging/pull/5976
* DEB: https://github.com/theforeman/foreman-packaging/pull/5978

**Comment by lzap** [comment]
So RPM was merged into nightly and I just raised cherry pick request. Unfortunately, we forgot to update also the debian package. This needs to be done, @rabajaj0509 please take a look. Cherry picks into 2.3:

* RPM: https://github.com/theforeman/foreman-packaging/pull/6016
* DEB: TBD

**Pull request merged**
