### PR TITLE
Fixes #19231 - better error for refresh fact

### PR DESCRIPTION
**Pull request by lzap**
Debugging impossible without this.

### CODE REVIEW

**Comment by ares** [comment]
LGTM

**Review by timogoebel — APPROVED** [review]
👍 on 💚 tests

**Comment by lzap** [comment]
Thanks guys, no typos, all green!

**Comment by lzap** [comment]
Oh man, I just force-pushed this branch, do not merge.

**Comment by lzap** [comment]
Fixed sorry. Git did not like me today.

**Comment by timogoebel** [comment]
Merged, thanks @lzap!

**Pull request merged**
