### PR TITLE
Fixes #31207 - add github actions

### PR DESCRIPTION
**Pull request by rabajaj0509**
These github actions will enable regression JS tests. It will also look out for code quality and prompt with suitable suggestions.

As a follow up I will add the caching to this github action. Let me know your thoughts @laviro :+1:

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
@rabajaj0509 did you got it working on your fork?
I know that GH actions first need to get merged in order to work for new pull requests,
can you share your fork's working action link here?

**Comment by rabajaj0509** [comment]
> @rabajaj0509 did you got it working on your fork?

Yup :smile: 

> I know that GH actions first need to get merged in order to work for new pull requests,
> can you share your fork's working action link here?

There you go: https://github.com/rabajaj0509/foreman_discovery/actions/runs/368219257

**Review by Ron-Lavi — APPROVED** [review]
LGTM, thanks @rabajaj0509 !

**Comment by lzap** [comment]
I don't know why tests are timing out on 2.7 ruby, I asked on discourse. I have no comments on the JS tho, feel free to merge or let me know when to merge.

**Comment by Ron-Lavi** [comment]
We can merge this in my opinion,
tested and everything works as it used to + now we will have the JS tests running :+1:

**Comment by rabajaj0509** [comment]
I would just want to try and run the tests once again, if the output (timeout) occurs then we can go ahead and merge the PR as is.

**Comment by rabajaj0509** [comment]
[test discovery]

**Comment by rabajaj0509** [comment]
[test]

**Comment by rabajaj0509** [comment]
[test]

**Comment by rabajaj0509** [comment]
[test discovery]

**Review by Ron-Lavi — APPROVED** [review]

**Comment by lzap** [comment]
Thanks guys.

**Pull request merged**
