### PR TITLE
[Do not merge] Fix parser after extraction of primary interface

### PR DESCRIPTION
**Pull request by ares**
This is to be merged after https://github.com/theforeman/foreman/pull/1988 gets in.

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm it does not work for me. This is what I get when I try to provision a discovered host.

```
RuntimeError (Host::Base#name= delegated to primary_interface.name=, but primary_interface is nil: #<Host::Managed id: 102, name: "mac5254005c4e73", last_compile: nil, last_freshcheck: nil, last_report: "2015-01-06 10:39:43", updated_at: "2015-01-06 10:39:46", source_file_id: nil, created_at: "2015-01-06 10:39:43", root_pass: nil, serial: nil, puppet_status: 0, architecture_id: nil, operatingsystem_id: nil, environment_id: nil, ptable_id: nil, medium_id: nil, build: false, comment: nil, disk: nil, installed_at: nil, model_id: 1, hostgroup_id: nil, owner_id: nil, owner_type: nil, enabled: true, puppet_ca_proxy_id: nil, managed: false, use_image: nil, image_file: nil, uuid: nil, compute_resource_id: nil, puppet_proxy_id: nil, certname: nil, image_id: nil, organization_id: 3, location_id: 2, type: "Host::Managed", otp: nil, realm_id: nil, compute_profile_id: nil, provision_method: nil, grub_pass: "", discovery_rule_id: nil>):
  app/models/host/base.rb:75:in `rescue in name='
  app/models/host/base.rb:72:in `name='
  app/controllers/hosts_controller.rb:532:in `process_hostgroup'
  app/controllers/concerns/application_shared.rb:13:in `set_timezone'
  app/models/concerns/foreman/thread_session.rb:33:in `clear_thread'
  lib/middleware/catch_json_parse_errors.rb:9:in `call'
```

**Comment by lzap** [comment]
@GregSutcliffe we'd need a similar but working patch that would work with stable and develop in our RC1

**Comment by GregSutcliffe** [comment]
@lzap your issue is a different one, this fixes an issue with db:migrate. +1 to merge this, I'm investigating the provisioning issue now.

**Comment by lzap** [comment]
Good news, merging this one as 3b34c81 thanks @ares !

Waiting for your investigation. My reproducer was - boot the foreman up... :-)

**Comment by lzap** [comment]
Closing for now, please reopen at will.

**Pull request closed without merging**
