### PR TITLE
Rails 5.2 upgrade config/as_deprecation_whitelist.yaml

### PR DESCRIPTION
**Pull request by lzap**
This should help with getting develop tests green until Rails 5.2 upgrade is complete.

### CODE REVIEW

**Comment by lzap** [comment]
@mmoll is my understanding correct that if there is a change in core which makes callstack different this won't work anymore and we need to pull whitelist changes again?

**Comment by lzap** [comment]
[test]

**Comment by mmoll** [comment]
http://ci.theforeman.org/job/test_plugin_pull_request/4903/

**Comment by lzap** [comment]
Replaced with: https://github.com/theforeman/foreman_discovery/pull/427

**Pull request closed without merging**
