### PR TITLE
Fixes #25101 - append stage2 for Atomic OS

### PR DESCRIPTION
**Pull request by lzap**
Also cleans option handling a bit.

### CODE REVIEW

**Comment by lzap** [comment]
Failure parsing Discovery Red Hat kexec: bare backslash only allowed before newline. near line 24: "\",\\n\".freeze".

Weird.

**Comment by lzap** [comment]
Rebased this should pass now @rahulbajaj0509

**Comment by lzap** [comment]
I was thinking using snapshotting service, but long term we would like to move rendering tests into community-templates and then we would move discovery templates there as well.

**Comment by rabajaj0509** [comment]
@lzap smooth! thanks, merging this now :)

**Pull request merged**
