### PR TITLE
Refs #10365 - refactoring migration to delete tokens

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by lzap** [comment]
@ohadlevy to be honest I like the original solution more since we are trying to fix corrupted meta-database here.

**Comment by lzap** [comment]
Ok I am going to give this NACK because this is going downstream, I don't want to introduce mis-commits.

We are loading all tokens anyway so the ideal case is:

```
Host::Managed.joins(:token).pluck("tokens.id")
```

**Comment by lzap** [comment]
I see that we use `pluck("tokens.id")` on many places. If you want to @orrabin I can test that but you need to cherry-pick this as well. Up to you.

**Comment by ohadlevy** [comment]
@lzap i disagree, the initial merge was too quick imho.

if you have many hosts, this is going to be a slow migration, there is really no need for that regardless of how you use it in any downstream product.

**Comment by lzap** [comment]
@orrabin can you rebase using fastest pluck bit? I will re-test.

**Comment by orrabin** [comment]
@lzap I changed to pluck

**Comment by orrabin** [comment]
@lzap I'm changing back, pluck will return all of the tokens and not just the correct one

**Comment by lzap** [comment]
We need to get rid of that `map` call, otherwise it's not optimized. The amount of SQL is the same:

```
[1] pry(main)> Host::Managed.joins(:token).map(&:token).compact
2015-05-18 12:22:45 [D]   Host::Managed Load (0.4ms)  SELECT "hosts".* FROM "hosts" INNER JOIN "tokens" ON "tokens"."host_id" = "hosts"."id" WHERE "hosts"."type" IN ('Host::Managed')
2015-05-18 12:22:45 [D]   Token Load (0.2ms)  SELECT "tokens".* FROM "tokens" WHERE "tokens"."host_id" = 77 LIMIT 1
2015-05-18 12:22:45 [D]   Token Load (0.1ms)  SELECT "tokens".* FROM "tokens" WHERE "tokens"."host_id" = 83 LIMIT 1
2015-05-18 12:22:45 [D]   Token Load (0.1ms)  SELECT "tokens".* FROM "tokens" WHERE "tokens"."host_id" = 85 LIMIT 1
=> [#<Token id: 35, value: "5b2d7f56-8960-4c80-9200-7a7ae0a6872d", expires: "2015-05-12 11:05:47", host_id: 77>,
 #<Token id: 37, value: "a446d761-a762-49ad-af97-299066b36f6f", expires: "2015-05-18 05:39:02", host_id: 83>,
 #<Token id: 38, value: "2d17c932-6999-41bf-9a30-5ca06a4b1e3f", expires: "2015-05-18 07:33:35", host_id: 85>]
[2] pry(main)> Host::Managed.all.map(&:token).compact
2015-05-18 12:22:57 [D]   Host::Managed Load (0.5ms)  SELECT "hosts".* FROM "hosts" WHERE "hosts"."type" IN ('Host::Managed')
2015-05-18 12:22:57 [D]   Token Load (0.2ms)  SELECT "tokens".* FROM "tokens" WHERE "tokens"."host_id" = 77 LIMIT 1
2015-05-18 12:22:57 [D]   Token Load (0.2ms)  SELECT "tokens".* FROM "tokens" WHERE "tokens"."host_id" = 83 LIMIT 1
2015-05-18 12:22:57 [D]   Token Load (0.1ms)  SELECT "tokens".* FROM "tokens" WHERE "tokens"."host_id" = 85 LIMIT 1
=> [#<Token id: 35, value: "5b2d7f56-8960-4c80-9200-7a7ae0a6872d", expires: "2015-05-12 11:05:47", host_id: 77>,
 #<Token id: 37, value: "a446d761-a762-49ad-af97-299066b36f6f", expires: "2015-05-18 05:39:02", host_id: 83>,
 #<Token id: 38, value: "2d17c932-6999-41bf-9a30-5ca06a4b1e3f", expires: "2015-05-18 07:33:35", host_id: 85>]
```

**Comment by orrabin** [comment]
@lzap the joins prevents trying to go over the whole table of hosts so it's better then without the join.
Since pluck won't work here I'm not sure what will be better then map

**Comment by lzap** [comment]
Ok it looks like we will be removing this migraiton from discovery anyway. Then we can close this one as this was implemented in core properly now: https://github.com/theforeman/foreman/pull/2402

**Pull request closed without merging**
