### PR TITLE
Fix failing tests after the 6.1 upgrade

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
[test foreman_discovery]

**Comment by Ron-Lavi** [comment]
[test foreman_discovery]

**Comment by Ron-Lavi** [comment]
Looks like some tests are still failing :/

**Comment by stejskalleos** [comment]
@Ron-Lavi Aaaand it's green! :green_apple:

**Comment by Ron-Lavi** [comment]
Thanks @stejskalleos !

**Pull request merged**
