### PR TITLE
Fixes #12559 - Refresh Facts error reporting fixed

### PR DESCRIPTION
**Pull request by lzap**
We are letting those exceptions to go out of the app context.

### CODE REVIEW

**Comment by lzap** [comment]
@orrabin easy one as well, thanks!

**Comment by lzap** [comment]
Pushed!

**Comment by lzap** [comment]
Fixed tests!

**Comment by orrabin** [comment]
Nitpick - the commit says refresh_facts and it's actually fixing reboot too.
I'll test when Jenkins is done.

**Comment by lzap** [comment]
> Nitpick - the commit says refresh_facts and it's actually fixing reboot too.
> I'll test when Jenkins is done.

The report was on refresh_facts, but they are all same so I fixed
them... Do you want me to change the commit message? Maybe you can when
merging... Thanks!

## 

Later,
 Lukas #lzap Zapletal

**Comment by orrabin** [comment]
merged as 5ec1ccacb2b2cafff34a07d60964fa40b165e5d2, thanks @lzap!

**Pull request closed without merging**
