### PR TITLE
Bump 21.0.2

### PR DESCRIPTION
**Pull request by Ron-Lavi**

### CODE REVIEW

**Comment by stejskalleos** [comment]
https://github.com/theforeman/foreman-packaging/pull/8308
https://github.com/theforeman/foreman-packaging/pull/8309

**Comment by Ron-Lavi** [comment]
Hey @stejskalleos, I think this should go to packaging with Foreman 3.3, and for the develop branch we should release a new version soon

**Comment by stejskalleos** [comment]
> Hey @stejskalleos, I think this should go to packaging with Foreman 3.3, and for the develop branch we should release a new version soon

Well develop has the same latest version so I'll do cherry-pick to 3.3 later

**Comment by Ron-Lavi** [comment]
Though our develop branch is 22.0:
https://github.com/theforeman/foreman_discovery/blob/develop/lib/foreman_discovery/version.rb

**Comment by stejskalleos** [comment]
> Though our develop branch is 22.0: https://github.com/theforeman/foreman_discovery/blob/develop/lib/foreman_discovery/version.rb

Yeah I'll fix the PRs

**Comment by Ron-Lavi** [comment]
Thanks @stejskalleos !

**Pull request merged**
