### PR TITLE
updates for bs3

### PR DESCRIPTION
**Pull request by mmoll**
fixes #4425

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Thanks!

@abenari could you review?

**Comment by abenari** [comment]
+1 lgtm

**Comment by GregSutcliffe** [comment]
@mmoll can you fix the commit message please :)

**Comment by mmoll** [comment]
@GregSutcliffe done :bowtie:

**Comment by GregSutcliffe** [comment]
@mmoll @abenari the button works again (awesome) but if I select a host and then click Assign Org (or Loc) I get: http://pastie.org/8788532 - Delete renders the list of hosts to delete just fine though. Could one of you take a look and see if you can replicate?

**Comment by GregSutcliffe** [comment]
@mmoll @abenari ignore that - I was testing the permissions branch, which was causing issues. Reverted to develop and it seems fine :)

**Comment by GregSutcliffe** [comment]
Merged as 14080309415aedd02044772d91ee4587e890c752 - thanks @mmoll!

**Comment by mmoll** [comment]
this was merged, close.

**Pull request closed without merging**
