### PR TITLE
Fixes #9021 - added scoped_search to discovery rule

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by lzap** [comment]
I will merge post 2.0 to prevent git conflicts.

**Comment by lzap** [comment]
Two problems:

1) Searching in New Rule - Search does not work anymore. This was the reason why I removed it from main screen.

2) When I entrer "enabled" in the main screen searchbox, I get weird error "could not verify 'enabled' type". But the JS call ends with 200 OK.

Please rebase as well.

**Comment by lzap** [comment]
Any update on this one?

**Comment by ohadlevy** [comment]
why close?

**Comment by orrabin** [comment]
it conflicts with the search in the rule itself

**Pull request closed without merging**
