### PR TITLE
fixes #22083 - replace deprecated am dirty methods

### PR DESCRIPTION
**Pull request by timogoebel**
Full disclosure: This is untested.

### CODE REVIEW

**Comment by mmoll** [comment]
I think it would be good to remove `config/as_deprecation_whitelist.yaml` from the repo.

**Comment by timogoebel** [comment]
@mmoll: Yes, definitely. If you open a PR, I'll be happy to merge.

**Comment by mmoll** [comment]
#401

**Comment by mmoll** [comment]
http://ci.theforeman.org/job/test_plugin_pull_request/4477 💔

**Comment by lzap** [comment]
Thanks @timogoebel a bunch. What is the status? When I run tests locally there are 5 failures.

**Comment by timogoebel** [comment]
@lzap: I guess, someone (TM) has to fix the tests. I'm currently doing some consulting work, will take a look next week when I'm back in the office. If you need this sooner, feel free to take it over. I don't mind.

**Comment by rabajaj0509** [comment]
@timogoebel seems that you are a little busy, I shall take care of this one :)

**Comment by timogoebel** [comment]
@rahulbajaj0509: Thanks, you are great!

**Comment by mmoll** [comment]
I'd recommend to wait for Rails 5.2 support to arrive (or to test with the rails_52 branch in my foreman fork), otherwise it's not easy to tell if a method needs to get changed or not.

**Comment by rabajaj0509** [comment]
@mmoll  is this pr workable now?

**Comment by mmoll** [comment]
If you want to test this, you'd need to use my rails_52 branch.

**Comment by ik5** [comment]
what is the status of this PR?
I want to remove my changes but they are needed for Rails 5.2 migrations, will it be merged soon?

**Comment by timogoebel** [comment]
@ik5: I don't mind closing this PR.

**Comment by ik5** [comment]
@timogoebel please don't, because you solve more things, I just want to remove from my PR two fixes that you made, but I need to know that this PR will be ready when foreman with Rails 5.2 will be out... or at least will be merged at some point :)

**Comment by lzap** [comment]
Sorry guys for the huge delay, just one more test to fix and we can retrigger everything and start merging!

**Comment by lzap** [comment]
Discovery develop is finally green again, please rebase to retest on jenkins.

**Comment by lzap** [comment]
Not being familiar with Rails5.2 changes, what is better than? `type_previously_changed?` change made by @ik5 or `will_save_change_to_attribute` and the other by @timogoebel ?

**Comment by lzap** [comment]
I am a bit confused, do we need both PRs or just one?

**Comment by lzap** [comment]
I am assuming I need to test this with this branch, can you confirm?

https://github.com/theforeman/foreman/pull/5836

**Comment by ik5** [comment]
@lzap yes, because we plan to move to rails 5.2.1 soon, and Timo's work should work with that as well

**Comment by lzap** [comment]
Tests are failing locally, is this supposed to be backward compatible or not? If not than I am going to merge this on the same day once core is merged.

**Comment by timogoebel** [comment]
Rebased.

**Comment by lzap** [comment]
Thank you very much for your contribution, this is now merged.

**Pull request merged**
