### PR TITLE
Fixes #9306 - added missing view_* permissions

### PR DESCRIPTION
**Pull request by lzap**
@orrabin reproduced a bug you reported, can you test?

When you were testing similar PR
https://github.com/theforeman/foreman_discovery/pull/252 you verified it
without need of adding the permission. But I believe the permission will not be
added automatically and we need a migration.

For this PR I needed to manually add the permission in the Role via UI to get
it working. Can you confirm? In that case, we need a migration similar to
a6826bee71d7818959aca7dbbba035fb94a8c204

### CODE REVIEW

**Comment by lzap** [comment]
We just found similar issue with OS: https://github.com/theforeman/foreman_discovery/pull/284

I think we either need to name all the permissions in the "Discovery Reader" role.

**Comment by lzap** [comment]
We will likely fix this in #284 - then we can close this one.

**Comment by lzap** [comment]
Looks like we are missing lot of view_ permissions, for this reason Discovery Manager was unable to provision correctly. This fixes both auto and UI process. Finally now we have a good test for UI provisioning - it checks all important fields.

I am including a migration that adds all required view permissions, we need to warn users in the readme notes for 6.0 release, but I don't see big security impact. Opinion @dLobatog ?

I stumbled upon small bug which I reported separately: http://projects.theforeman.org/issues/15735

Ready for review.

**Comment by lzap** [comment]
Forgot to git add the migration file! Fixed.

**Comment by lzap** [comment]
I also moved "Discovered facts import unsuccessful, skipping auto provisioning" message a bit, it was reported in case import _was_ successful but auto provisioning was not triggered.

**Comment by dLobatog** [comment]
Fair enough - please leave a big warning on the release notes or the manual the role permissions scope is much larger than it was, it can catch people by surprise.

**Comment by dLobatog** [comment]
Merged as 1d7465f68110ad249f2b81c540767e22510d3416, thanks @lzap!

**Pull request closed without merging**
