### PR TITLE
Fixes #19501 - [PatternFly Consistent] capitalize the first letter of every word

### PR DESCRIPTION
**Pull request by junezhang**
Based on PatternFly Terminology and Wording Guideline[1], suggest all the headline style to keep consistent to capitalize the first letter of every word.

[1]http://www.patternfly.org/styles/terminology-and-wording/#capitalization

### CODE REVIEW

**Comment by junezhang** [comment]
test

**Comment by ohadlevy** [comment]
[ok to test]

**Comment by ohadlevy** [comment]
[test]

**Comment by junezhang** [comment]
[test]

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Merged, thanks @junezhang.

**Pull request merged**
