### PR TITLE
fixes #2716 error in discovery plugin menu and user without permissions

### PR DESCRIPTION
**Pull request by abenari**
this pull request depend on  https://github.com/theforeman/foreman/pull/750

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Looks good, happy to merge once foreman#750 is in

**Comment by domcleal** [comment]
Should we do this by matching text instead?

We could change Foreman to use N_("Provisioning") and translate the string closer to the page render, then search for the string "Provisioning" from the plugin (ditto for position inside the menu, which [I want to sort](http://projects.theforeman.org/issues/2688) closer to rendering anyway).  It'd be more robust then if we changed the menu between versions.

**Comment by GregSutcliffe** [comment]
@domcleal I agree, but that's a big change, and if we release 1.2 in this state then it will break the UI for non-admin users of a discovery-enabled system. I vote we merge this and review how plugins hook into the menu as soon as possible in the 1.3 cycle.

**Comment by abenari** [comment]
@domcleal I was looking at changing the menu implementation from a structure to class, and maybe using the same code as katello project does and use method  such as insert_after instead of having the plugin know about the internal data structure.
The a larger change might take time until we agree on a common solution with katello project.I don't think we need to postpone this simple fix.

**Comment by domcleal** [comment]
Ok, thanks for the explanation @abenari, that works for me.

**Comment by GregSutcliffe** [comment]
Merged as eab5fa3, thanks @abenari !

**Pull request closed without merging**
