### PR TITLE
Refs #16899 - core helper is renamed in 1.14

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
Thanks @ares  - I realized after merging it should have a different issue number though...

**Comment by ares** [comment]
you mean a separate issue for the plugin?

**Comment by dLobatog** [comment]
Yeah, refs is fine for fixing an issue again in the same repo, but not across different projects I believe

**Comment by ares** [comment]
I thought that was applicable only in core, plugins (or at least rex) didn't enforce that policy). Anyway next time I can create separate issues.

**Pull request merged**
