### PR TITLE
GitHub action for ruby tests

### PR DESCRIPTION
**Pull request by stejskalleos**
Note: Rubocop will be done in https://github.com/theforeman/foreman_discovery/pull/602/files

### CODE REVIEW

**Comment by stejskalleos** [comment]
@nofaralfasi review please

**Comment by stejskalleos** [comment]
foreman_discovery is failing but it's not caused by these changes, I'll ask the platform team to investigate what's going on there.

**Comment by stejskalleos** [comment]
@nofaralfasi review please

**Comment by nofaralfasi** [comment]
LGTM :+1:

**Review by nofaralfasi — APPROVED** [review]

**Pull request merged**
