### PR TITLE
fixes #9527 - refactor multiple actions

### PR DESCRIPTION
**Pull request by shlomizadok**
refactor multiple actions to work with refactored foreman's multi action

### CODE REVIEW

**Comment by orrabin** [comment]
@shlomizadok now the selection works and the modal for the action opens up but the submit button doesn't work, not sure if it's related or another issue.

**Comment by shlomizadok** [comment]
@orrabin now fixed too.

**Comment by orrabin** [comment]
@shlomizadok looks good

**Comment by orrabin** [comment]
[test], previous test was aborted

**Comment by lzap** [comment]
@shlomizadok can you please attach link to the patch in foreman core that is relevant? Thanks you! LGTM

**Comment by shlomizadok** [comment]
@lzap @orrabin @GregSutcliffe - core patch: https://github.com/theforeman/foreman/commit/8f38e945032c97cf6f2c01ba9080f3129f1327e6

**Comment by lzap** [comment]
Thanks. I've rebased but this is what I see when I try to "Assign Organization":

**Comment by shlomizadok** [comment]
@lzap -- No clue, as no css was changed both here and in core.
Mine looks like:
untitled

@GregSutcliffe @orrabin can you please test too.

**Comment by orrabin** [comment]
@shlomizadok this works fine for me.
@lzap maybe you have the cookie from before the patch that you need to delete first?

**Comment by lzap** [comment]
Cookie was the issue, log-out, log-in and it works now. Great. Merged as d1680aba5152ac38d69ec4c3f9fceeba80e21fc2 thank you @shlomizadok !

**Pull request closed without merging**
