### PR TITLE
Fixes #22520 - add hover effect to tables

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]
👍  when the core PR is merged.

**Comment by lzap** [comment]
Core merged, it kinda looks weird for tables with odd number of records, but that's not discovery business.

discovery rules

**Comment by lzap** [comment]
It renders fine now, also we will be changing pagination style to match Patternfly for rules. All good. Thanks.

**Review by lzap — APPROVED** [review]
LGTM

**Pull request merged**
