### PR TITLE
Bkearney/downstream strings

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by bkearney** [comment]
@lzap, I changed the script to use this command:

msgmerge --no-fuzzy-matching -C $up_po -o $up_po $down_po $up_pot

and it did not result in a change, so I believe fuzzy matching is not an issue here.

**Comment by bkearney** [comment]
@lzap I modified the script to remove blank lines, it is a new commit.
@claer I made the changes you requested _except_ for the menu items. I recall us telling the translators they are required. I will ask on the -dev mailing list. If I am incorrect, I will add those changes in a new commit. 

Once we agree, I am happy to sqaush this.

**Comment by bkearney** [comment]
@claer I have removed the model names in the four languages I saw them. This, I believe, is the last of your comments. When you all are happy I am happy to sqash into a single commit. Or, if you prefer, one commit for the pull from tx and another for the downstream changes.

**Comment by claer** [comment]
Everything looks good for me, go ahead :)

**Comment by lzap** [comment]
Please keep two commits. But I still see many fuzzy translations and they are mostly wrong! Show me your script please.

**Comment by lzap** [comment]
For now you can remove them manually (search for the comment "fuzzy"), put blank translation instead the fuzzy one. But this should be fixed in your script.

**Comment by bkearney** [comment]
@lzap, this is the script: https://gist.github.com/bkearney/64b5365912c16ca3b986

**Comment by bkearney** [comment]
@lzap, @claer I  have rebased the code, and squashed this into two commits. All of the changes you all asked for are in the new PR.

**Comment by bkearney** [comment]
[test]

**Comment by lzap** [comment]
Merged as f61a39cde0d6f87bd227d119a77e36db82fb484d, thank you!

**Comment by lzap** [comment]
Found some issues, will fix:

```
locale/pt_BR/foreman_discovery.po:118: keyword "Habilitado" unknown
locale/pt_BR/foreman_discovery.po:118:18: syntax error
locale/pt_BR/foreman_discovery.po:119: end-of-line within string
msgfmt: found 3 fatal errors
```

**Comment by lzap** [comment]
Fixed as ab906af745ae645614cccc6cd4be30f8f23c6709. That was the reason why unit tests failed by the way. :-) My bad.

**Comment by bkearney** [comment]
@lzap to confirm, you pushed he strings (po files) to transifex?

**Comment by lzap** [comment]
> @lzap to confirm, you pushed he strings (po files) to transifex?

Yes, I confirm.

## 

Later,
 Lukas #lzap Zapletal

**Pull request closed without merging**
